### ISSUE TITLE
Las funciones deben servir para cualquier micro

### ISSUE THREAD

**Issue by ZabreLight** [hernan-arga/TP-funcional-paradigmas#1]
La funcion nop como todas las otras deben poder ser usadas con cualquier microprocesador, no solo con el  `xt8088 `

`nop = xt8088 {programCounter = programCounter xt8088 + 1} `

**Comment by hernan-arga** [comment]
@ZabreLight ¿Estaria mal si a la funcion nop se le pasa como parametro el tipo de microcontrolador de la siguiente forma?
`nop unMicro = unMicro {programCounter = programCounter xt8088 + 1}`

solo que asi cada vez que use esta funcion tengo que especficarle el controlador.

**Comment by ZabreLight** [comment]
@hernan-arga la solucion que estas pasando esta bien. El problema que hay es de concepto. Vos a la funcion no le estas pasando como parametro el tipo del micro. Le estas pasando un micro

`nop unMicro = unMicro {programCounter = programCounter unMicro + 1}`

La idea es que uses el micro como constructor, de esta manera el nuevo micro que se creara va a tener todos los campos iguales que el constructor excepto el que vos cambias, que en este caso seria el `programCounter`. 

Fijate que el tipo de esta funcion seria

`nop :: Micro -> Micro`

**Comment by hernan-arga** [comment]
@ZabreLight Si, no me habia dado cuenta de modificarlo cuando te lo pregunte. Ahi lo actualizo, gracias por responder.
