### ISSUE TITLE
Hay funciones innecesarias

### ISSUE THREAD

**Issue by ZabreLight** [hernan-arga/TP-funcional-paradigmas#3]
Todas estas funciones no son necesarias, al crear el data ya se crean las funciones `accessors` con el nombre de cada uno de los atributos 

```
-- RESTRICCIONES
programCounter :: Microprocesador -> Int
programCounter unMicrocontrolador = pc unMicrocontrolador
acumuladorA :: Microprocesador -> Int
acumuladorA unMicrocontrolador = a unMicrocontrolador
acumuladorB :: Microprocesador -> Int
acumuladorB unMicrocontrolador = b unMicrocontrolador
memoria :: Microprocesador -> [Int]
memoria unMicrocontrolador = memoriaDeDatos unMicrocontrolador
mensajeError :: Microprocesador -> String
mensajeError unMicrocontrolador = etiqueta unMicrocontrolador
```

**Comment by hernan-arga** [comment]
@ZabreLight No entendi, directamente las borro estas porque automaticamente ya estan los acccessors o tengo que crear los accessors?

**Comment by ZabreLight** [comment]
@hernan-arga Sisi borralas, el data ya te genera los accessors directamente. Si vos tenes un data persona 

`Persona {nombre :: String, edad :: Int, dni :: Int}`

Dentro de cualquier funcion podes usar los accessors que Persona te da. Supongamos que en una funcion recibimos una persona y tenemos que decir si es mayor de edad.

`funcion unaPersona = edad unaPersona > 18`

La funcion edad no la tenemos que declarar en ningun lado. El solo hecho de tener un data persona nos da las funciones `nombre` `edad` y `dni`

Con el micro pasa lo mismo, al haber declarado un data Micro ya tenemos los accessors a todos los atributos del micro acumuladorA, acumuladorB, etc...

**Comment by hernan-arga** [comment]
@ZabreLight ahi entendi, gracias.
