### ISSUE TITLE
Addr base 0

### ISSUE THREAD

**Issue by ZabreLight** [hernan-arga/TP-funcional-paradigmas#8]
Vi que en varios lugares hacen `addr - 1` para que el addr este en base 0. Asuman que ya viene en base 0, asi no tienen que hacer `addr - 1`.

**Comment by abrildelburgo** [comment]
@ZabreLight Hola Lucas! Te hago una consulta con este issue, en el enunciado del tp dice "Una gran cantidad de posiciones que conforman la memoria de datos. Consideramos que la memoria comienza a partir de la posición 1" . Mas allá de eso, si uso una lista, siempre la tomo desde la posición 0 aunque diga eso? Gracias

**Comment by ZabreLight** [comment]
@abrildelburgo Este issue es algo que les sugeri para que el codigo les quede mas lindo. Uno siempre dice que una memoria tiene x cantidad de valores, entonces si una memoria tiene 1024 posiciones, se sabe que va desde la 0 hasta la 1023 ya que la arq de los micros usa base 0, al igual que los vectores.

Lo que yo les sugeria es que asuman que el usuario de su programa va a saber esto y siempre va a cargar valores en base 0. Entonces si el usuario quiere acceder a la primera posicion va a saber que esta en base 0 y va a introducir el 0. Si quiere ingresar a la ultima no va a introducir 1024, va a introducir 1023.

Mas alla de todo. Esto es un concepto que escapa a la materia y al tp. Yo se los marcaba para que no tuvieran que restarle 1 en todos lados. A veces esta bueno asumir cosas, entonces en vez de decir:
"El usuario es un idiota que va a meter 1 para la primera posicion" 
Podemos decir:
"El usuario es una persona competente que esta al tanto de la arq de un micro y sabe que la primera posicion es la 0"
